package trans

const (
	EMAIL_INVITE_SUBJ = "EMAIL_INVITE_SUBJ"
	EMAIL_INVITE_HTML = "EMAIL_INVITE_HTML"
	EMAIL_INVITE_TEXT = "EMAIL_INVITE_TEXT"
)

const (
	MESSAGE_TEXT_INVITE_CREATED             = "MESSAGE_TEXT_INVITE_CREATED"
	MESSAGE_TEXT_TRANSFER_CREATION_CANCELED = "MESSAGE_TEXT_TRANSFER_CREATION_CANCELED"

	MESSAGE_TEXT_NOTHING_TO_CANCEL                 = "MESSAGE_TEXT_NOTHING_TO_CANCEL"
	MESSAGE_TEXT_SETTINGS                          = "MESSAGE_TEXT_SETTINGS"
	MESSAGE_TEXT_NOT_IMPLEMENTED_YET               = "MESSAGE_TEXT_NOT_IMPLEMENTED_YET"
	MESSAGE_TEXT_ONBOARDING_ASK_TO_CHOOSE_LANGUAGE = "MESSAGE_TEXT_ONBOARDING_ASK_TO_CHOOSE_LANGUAGE"
	MESSAGE_TEXT_WHATS_NEXT                        = "What's next?"

	MESSAGE_TEXT_UNKNOWN_LANGUAGE = "MESSAGE_TEXT_UNKNOWN_LANGUAGE"

	MESSAGE_TEXT_
	MESSAGE_TEXT_HISTORY = "MESSAGE_TEXT_HISTORY"
	MESSAGE_TEXT_WELCOME = "MESSAGE_TEXT_WELCOME"

	MESSAGE_TEXT_INVITE_BY_EMAIL    = "MESSAGE_TEXT_INVITE_BY_EMAIL"
	MESSAGE_TEXT_INVITE_BY_SMS      = "MESSAGE_TEXT_INVITE_BY_SMS"
	MESSAGE_TEXT_INVITE_BY_TELEGRAM = "MESSAGE_TEXT_INVITE_BY_TELEGRAM"

	MESSAGE_TEXT_INVALID_EMAIL        = "MESSAGE_TEXT_INVALID_EMAIL"
	MESSAGE_TEXT_INVALID_PHONE_NUMBER = "MESSAGE_TEXT_INVALID_PHONE_NUMBER"
	MESSAGE_TEXT_NO_CONTACT_RECEIVED  = "MESSAGE_TEXT_NO_CONTACT_RECEIVED"

	MESSAGE_TEXT_HISTORY_ROW_FROM_USER_WITH_NAME = "MESSAGE_TEXT_HISTORY_ROW_FROM_USER_WITH_NAME"
	MESSAGE_TEXT_HISTORY_ROW_TO_USER_WITH_NAME = "MESSAGE_TEXT_HISTORY_ROW_TO_USER_WITH_NAME"

	MESSAGE_TEXT_INVALID_INT = "MESSAGE_TEXT_INVALID_INT"

	MESSAGE_TEXT_OK_PLEASE_TRY_AGAIN = "MESSAGE_TEXT_OK_TRY_AGAIN"

	MESSAGE_TEXT_ONBOARDING_TELL_ABOUT_INVITES = "MESSAGE_TEXT_ONBOARDING_TELL_ABOUT_INVITES"
	MESSAGE_TEXT_WRONG_EMAIL                   = "MESSAGE_TEXT_WRONG_EMAIL"
	MESSAGE_TEXT_WRONG_PHONE_NUMBER            = "MESSAGE_TEXT_WRONG_PHONE_NUMBER"

	MESSAGE_TEXT_ASK_INVITE_CHANNEL = "MESSAGE_TEXT_ASK_INVITE_CHANNEL"
	MESSAGE_TEXT_PLEASE_PROVIDE_YOUR_EMAIL        = "MESSAGE_TEXT_PLEASE_PROVIDE_YOUR_EMAIL"
	MESSAGE_TEXT_PLEASE_PROVIDE_YOUR_PHONE_NUMBER = "MESSAGE_TEXT_PLEASE_PROVIDE_YOUR_PHONE_NUMBER"
	MESSAGE_TEXT_PLEASE_ENTER_INVITE_CODE         = "MESSAGE_TEXT_PLEASE_ENTER_INVITE_CODE"

	MESSAGE_TEXT_USER_EMAIL_FOR_INVITE_RECEIVED = "MESSAGE_TEXT_USER_EMAIL_FOR_INVITE_RECEIVED"
	MESSAGE_TEXT_USER_CONTACT_FOR_INVITE_RECEIVED = "MESSAGE_TEXT_USER_CONTACT_FOR_INVITE_RECEIVED"

	MESSAGE_TEXT_WRONG_INVITE_CODE  = "MESSAGE_TEXT_WRONG_INVITE_CODE"
	MESSAGE_TEXT_CHOOSE_UI_LANGUAGE = "MESSAGE_TEXT_CHOOSE_UI_LANGUAGE"
	MESSAGE_TEXT_ABOUT_INVITES      = "MESSAGE_TEXT_ABOUT_INVITES"

	MESSAGE_TEXT_USER_BLOCKED_TRANSFER_NOTIFICATIONS_BY = "MESSAGE_TEXT_USER_BLOCKED_TRANSFER_NOTIFICATIONS_BY"

	MESSAGE_TEXT_ASK_LENDING_TYPE         = "MESSAGE_TEXT_ASK_LENDING_TYPE"
	MESSAGE_TEXT_ASK_LENDING_AMOUNT       = "MESSAGE_TEXT_ASK_LENDING_AMOUNT"
	MESSAGE_TEXT_ASK_LENDING_COUNTERPARTY = "MESSAGE_TEXT_ASK_LENDING_COUNTERPARTY"
	MESSAGE_TEXT_TRANSFER_FROM_USER_COMPLETED        = "MESSAGE_TEXT_TRANSFER_FROM_USER_COMPLETED"
	MESSAGE_TEXT_YOU_CAN_SEND_RECEIPT     = "MESSAGE_TEXT_YOU_CAN_SEND_RECEIPT"

	MESSAGE_TEXT_ASK_BORROWING_TYPE         = "MESSAGE_TEXT_ASK_BORROWING_TYPE"
	MESSAGE_TEXT_ASK_BORROWING_AMOUNT       = "MESSAGE_TEXT_ASK_BORROWING_AMOUNT"
	MESSAGE_TEXT_ASK_BORROWING_COUNTERPARTY = "MESSAGE_TEXT_ASK_BORROWING_COUNTERPARTY"
	MESSAGE_TEXT_TRANSFER_TO_USER_COMPLETED        = "MESSAGE_TEXT_TRANSFER_TO_USER_COMPLETED"
	MESSAGE_TEXT_YOUR_ABOUT_ADS = "MESSAGE_TEXT_YOUR_ABOUT_ADS"
	MESSAGE_TEXT_YOUR_AD_COULD_BE_HERE      = "MESSAGE_TEXT_YOUR_AD_COULD_BE_HERE"
	MESSAGE_TEXT_ASK_NEW_COUNTERPARTY_NAME  = "MESSAGE_TEXT_ASK_NEW_COUNTERPARTY_NAME"

	MESSAGE_TEXT_DUE_ON = "MESSAGE_TEXT_DUE_ON"
	MESSAGE_TEXT_NOTE = "MESSAGE_TEXT_NOTE"
	MESSAGE_TEXT_COMMENT = "MESSAGE_TEXT_COMMENT"

	MESSAGE_TEXT_ASK_DUE_DATE = "MESSAGE_TEXT_ASK_DUE_DATE"

	MESSAGE_TEXT_FAILED_TO_DELETE_USER      = "MESSAGE_TEXT_FAILED_TO_DELETE_USER"
	MESSAGE_TEXT_USER_DELETED               = "MESSAGE_TEXT_USER_DELETED"
	MESSAGE_TEXT_ASK_PRIMARY_CURRENCY       = "MESSAGE_TEXT_ASK_PRIMARY_CURRENCY"
	MESSAGE_TEXT_PRIMARY_CURRENCY_IS_SET_TO = "MESSAGE_TEXT_PRIMARY_CURRENCY_IS_SET_TO"

	MESSAGE_TEXT_BALANCE_IS_ZERO                                   = "MESSAGE_TEXT_BALANCE_IS_ZERO"
	MESSAGE_TEXT_BALANCE_CURRENCY_TOTAL_INTRO                      = "MESSAGE_TEXT_BALANCE_CURRENCY_TOTAL_INTRO"
	MESSAGE_TEXT_BALANCE_SINGLE_CURRENCY_COUNTERPARTY_DEBT_TO_USER = "MESSAGE_TEXT_BALANCE_SINGLE_CURRENCY_COUNTERPARTY_DEBT_TO_USER"
	MESSAGE_TEXT_BALANCE_SINGLE_CURRENCY_COUNTERPARTY_DEBT_BY_USER = "MESSAGE_TEXT_BALANCE_SINGLE_CURRENCY_COUNTERPARTY_DEBT_BY_USER"

	MESSAGE_TEXT_BALANCE_CURRENCY_ROW_DEBT_TO_USER = "MESSAGE_TEXT_BALANCE_CURRENCY_ROW_DEBT_TO_USER"
	MESSAGE_TEXT_BALANCE_CURRENCY_ROW_DEBT_BY_USER = "MESSAGE_TEXT_BALANCE_CURRENCY_ROW_DEBT_BY_USER"

	MESSAGE_TEXT_PLEASE_WAIT_WHILE_WE_GENERATE_INVITE_CODE = "MESSAGE_TEXT_PLEASE_WAIT_WHILE_WE_GENERATE_INVITE_CODE"
	MESSAGE_TEXT_RETURN_ASK_TO_CHOOSE_COUNTERPARTY         = "MESSAGE_TEXT_RETURN_ASK_TO_CHOOSE_COUNTERPARTY"
	MESSAGE_TEXT_CHOOSE_DEBT_THAT_HAS_BEEN_RETURNED = "MESSAGE_TEXT_CHOOSE_DEBT_THAT_HAS_BEEN_RETURNED"
	MESSAGE_TEXT_COUNTERPARTY_OWES_YOU_SINGLE_DEBT_IS_IT_RETURNED_IN_FULL = "MESSAGE_TEXT_COUNTERPARTY_OWES_YOU_SINGLE_DEBT_IS_IT_RETURNED_IN_FULL"
	MESSAGE_TEXT_YOU_OWE_TO_COUNTERPARTY_SINGLE_DEBT_IS_IT_RETURNED_IN_FULL = "MESSAGE_TEXT_YOU_OWE_TO_COUNTERPARTY_SINGLE_DEBT_IS_IT_RETURNED_IN_FULL"

	MESSAGE_TEXT_YOU_HAVE_RETURNED = "MESSAGE_TEXT_YOU_HAVE_RETURNED"
	MESSAGE_TEXT_YOU_HAVE_GOT_BACK = "MESSAGE_TEXT_YOU_HAVE_GOT_BACK"

	MESSAGE_TEXT_RECEIPT_LINK = "MESSAGE_TEXT_RECEIPT_LINK"

	MESSAGE_TEXT_ASK_PHONE_NUMBER_OF_COUNTERPARTY = "MESSAGE_TEXT_ASK_PHONE_NUMBER_OF_COUNTERPARTY"
	MESSAGE_TEXT_ABOUT_PHONE_NUMBER_FORMAT = "MESSAGE_TEXT_ABOUT_PHONE_NUMBER_FORMAT"
	MESSAGE_TEXT_THIS_NUMBER_WILL_BE_USED_TO_SEND_RECEIPT = "MESSAGE_TEXT_THIS__NUMBER_WILL_BE_USED_TO_SEND_RECEIPT"

	BUTTON_TEXT_YOU_OWE_AMOUNT_TO_SOMEONE = "BUTTON_TEXT_YOU_OWE_AMOUNT_TO_SOMEONE"
	BUTTON_TEXT_SOMEONE_OWES_TO_YOU_AMOUNT = "BUTTON_TEXT_SOMEONE_OWES_TO_YOU_AMOUNT"
	BUTTON_TEXT_DEBT_RETURNED_FULLY = "BUTTON_TEXT_DEBT_RETURNED_FULLY"
	BUTTON_TEXT_DEBT_RETURNED_PARTIALLY = "BUTTON_TEXT_DEBT_RETURNED_PARTIALLY"

	MESSAGE_TEXT_BALANCE_HEADER = "MESSAGE_TEXT_BALANCE_HEADER"
	INLINE_BUTTON_SHOW_FULL_HISTORY = "INLINE_BUTTON_SHOW_FULL_HISTORY"
	MESSAGE_TEXT_ASK_HOW_MUCH_HAS_BEEN_RETURNED = "MESSAGE_TEXT_ASK_HOW_MUCH_HAS_BEEN_RETURNED"
	MESSAGE_TEXT_INCORRECT_VALUE_NOT_A_NUMBER = "MESSAGE_TEXT_INCORRECT_VALUE_NOT_A_NUMBER"
	MESSAGE_TEXT_INCORRECT_VALUE_IS_NEGATIVE = "MESSAGE_TEXT_INCORRECT_VALUE_IS_NEGATIVE"
	MESSAGE_TEXT_ON_RETURN_USER_DOES_NOT_OWE_ANYTHING_TO_COUNTERPARTY_ANYMORE = "MESSAGE_TEXT_ON_RETURN_USER_DOES_NOT_OWE_ANYTHING_TO_COUNTERPARTY_ANYMORE"
	MESSAGE_TEXT_ON_RETURN_COUNTERPARTY_DOES_NOT_OWE_ANYTHING_TO_USER_ANYMORE = "MESSAGE_TEXT_ON_RETURN_COUNTERPARTY_DOES_NOT_OWE_ANYTHING_TO_USER_ANYMORE"
)

const (
	LINK_VIEW_RECEIPT = "LINK_VIEW_RECEIPT"
)

const (
	INLINE_RECEIPT_TITLE       = "INLINE_RECEIPT_TITLE"
	INLINE_RECEIPT_DESCRIPTION = "INLINE_RECEIPT_DESCRIPTION"
	INLINE_RECEIPT_MESSAGE     = "INLINE_RECEIPT_MESSAGE"

	INLINE_INVITE_TITLE       = "INLINE_INVITE_TITLE"
	INLINE_INVITE_DESCRIPTION = "INLINE_INVITE_DESCRIPTION"
	INLINE_INVITE_MESSAGE     = "INLINE_INVITE_MESSAGE"
)

const (
	COMMAND_TEXT_SEE_RECEIPT_DETAILS = "COMMAND_TEXT_SEE_RECEIPT_DETAILS"
	COMMAND_TEXT_ACCEPT_INVITE       = "COMMAND_TEXT_ACCEPT_INVITE"
	COMMAND_TEXT_MAIN_MENU_TITLE     = "Main /menu"
	COMMAND_TEXT_ON_SPECIFIC_DATE    = "COMMAND_TEXT_ON_SPECIFIC_DATE"
	COMMAND_TEXT_TOMORROW            = "COMMAND_TEXT_TOMORROW"
	COMMAND_TEXT_DAY_AFTER_TOMORROW  = "COMMAND_TEXT_DAY_AFTER_TOMORROW"
	COMMAND_TEXT_THIS_WEEK           = "COMMAND_TEXT_THIS_WEEK"
	COMMAND_TEXT_IN_FEW_MINUTES      = "COMMAND_TEXT_IN_FEW_MINUTES"
	COMMAND_TEXT_IN_1_WEEK           = "COMMAND_TEXT_IN_1_WEEK"
	COMMAND_TEXT_IN_1_MONTH          = "COMMAND_TEXT_IN_1_MONTH"
	COMMAND_TEXT_SET_DATE            = "COMMAND_TEXT_SET_DATE"

	COMMAND_TEXT_MONDAY    = "COMMAND_TEXT_MONDAY"
	COMMAND_TEXT_TUESDAY   = "COMMAND_TEXT_TUESDAY"
	COMMAND_TEXT_WEDNESDAY = "COMMAND_TEXT_WEDNESDAY"
	COMMAND_TEXT_THURSDAY  = "COMMAND_TEXT_THURSDAY"
	COMMAND_TEXT_FRIDAY    = "COMMAND_TEXT_FRIDAY"
	COMMAND_TEXT_SATURDAY  = "COMMAND_TEXT_SATURDAY"
	COMMAND_TEXT_SUNDAY    = "COMMAND_TEXT_SUNDAY"

	COMMAND_TEXT_YES_IT_HAS_RETURN_DEADLINE    = "COMMAND_TEXT_YES_IT_HAS_RETURN_DEADLINE"
	COMMAND_TEXT_NO_IT_CAN_BE_RETURNED_ANYTIME = "COMMAND_TEXT_NO_IT_CAN_BE_RETURNED_ANYTIME"
	COMMAND_TEXT_IT_CAN_BE_RETURNED_ANYTIME    = "COMMAND_TEXT_IT_CAN_BE_RETURNED_ANYTIME"

	MESSAGE_TEXT_PLEASE_CHOOSE_FROM_OPTIONS_PROVIDED = "MESSAGE_TEXT_PLEASE_CHOOSE_FROM_OPTIONS_PROVIDED"
	MESSAGE_TEXT_TRANSFER_ASK_FOR_NOTE_OR_COMMENT = "MESSAGE_TEXT_TRANSFER_ASK_FOR_NOTE_OR_COMMENT"
	MESSAGE_TEXT_TRANSFER_ASK_FOR_NOTE = "MESSAGE_TEXT_TRANSFER_ASK_FOR_NOTE"
	MESSAGE_TEXT_TRANSFER_ASK_FOR_COMMENT = "MESSAGE_TEXT_TRANSFER_ASK_FOR_COMMENT"
	MESSAGE_TEXT_TRANSFER_COMMENT_ADDED_ASK_FOR_NOTE = "MESSAGE_TEXT_TRANSFER_COMMENT_ADDED_ASK_FOR_NOTE"
	MESSAGE_TEXT_TRANSFER_NOTE_ADDED_ASK_FOR_COMMENT = "MESSAGE_TEXT_TRANSFER_NOTE_ADDED_ASK_FOR_COMMENT"

	COMMAND_TEXT_NO_COMMENT_OR_NOTE_FOR_TRANSFER = "COMMAND_TEXT_NO_COMMENT_OR_NOTE_FOR_TRANSFER"
	COMMAND_TEXT_NO_COMMENT_FOR_TRANSFER = "COMMAND_TEXT_NO_COMMENT_FOR_TRANSFER"
	COMMAND_TEXT_NO_NOTE_FOR_TRANSFER = "COMMAND_TEXT_NO_NOTE_FOR_TRANSFER"

	COMMAND_TEXT_ADD_NOTE_TO_TRANSFER = "COMMAND_TEXT_ADD_NOTE_TO_TRANSFER"
	COMMAND_TEXT_ADD_COMMENT_TO_TRANSFER = "COMMAND_TEXT_ADD_COMMENT_TO_TRANSFER"

	COMMAND_TEXT_CANCEL                    = "COMMAND_TEXT_CANCEL"
	COMMAND_TEXT_ADD_YOUR_OWN_OPTION       = "COMMAND_TEXT_ADD_YOUR_OWN_OPTION"
	COMMAND_TEXT_SETTINGS_PRIMARY_CURRENCY = "COMMAND_TEXT_SETTINGS_PRIMARY_CURRENCY"
	COMMAND_TEXT_LANGUAGE                  = "COMMAND_TEXT_LANGUAGE"
	COMMAND_TEXT_OTHER_WAYS_TO_SEND_INVITE = "COMMAND_TEXT_OTHER_WAYS_TO_SEND_INVITE"

	COMMAND_TEXT_INVITE_ME_BY_EMAIL = "COMMAND_TEXT_INVITE_ME_BY_EMAIL"
	COMMAND_TEXT_INVITE_ME_BY_SMS   = "COMMAND_TEXT_INVITE_ME_BY_SMS"

	COMMAND_TEXT_SEND_ME_NEW_INVITE = "COMMAND_TEXT_SEND_ME_NEW_INVITE"
	COMMAND_TEXT_SEND_ME_NEW_INVITE_BY_EMAIL = "COMMAND_TEXT_SEND_ME_NEW_INVITE_BY_EMAIL"
	COMMAND_TEXT_SEND_ME_NEW_INVITE_BY_SMS   = "COMMAND_TEXT_SEND_ME_NEW_INVITE_BY_SMS"
	COMMAND_TEXT_SEND_ME_NEW_INVITE_BY_TELEGRAM   = "COMMAND_TEXT_SEND_ME_NEW_INVITE_BY_TELEGRAM"

	COMMAND_TEXT_SEND_MY_PHONE_NUMBER = "COMMAND_TEXT_SEND_MY_PHONE_NUMBER"

	COMMAND_TEXT_SEND_BY_EMAIL      = "COMMAND_TEXT_SEND_BY_EMAIL"
	COMMAND_TEXT_SEND_BY_SMS        = "COMMAND_TEXT_SEND_BY_SMS"
	COMMAND_TEXT_INVITE_BY_TELEGRAM = "COMMAND_TEXT_INVITE_BY_TELEGRAM"


	COMMAND_TEXT_I_HAVE_INVITE              = "I_HAVE_INVITE"
	COMMAND_TEXT_MISTYPE_WILL_TRY_AGAIN     = "COMMAND_TEXT_MISTYPE_WILL_TRY_AGAIN"
	COMMAND_TEXT_TELL_ME_MORE_ABOUT_INVITES = "COMMAND_TEXT_TELL_ME_MORE_ABOUT_INVITES"

	COMMAND_TEXT_GAVE          = "COMMAND_TEXT_GAVE"
	COMMAND_TEXT_GOT           = "COMMAND_TEXT_GOT"
	COMMAND_TEXT_RETURN        = "COMMAND_TEXT_RETURN"
	COMMAND_TEXT_BALANCE       = "COMMAND_TEXT_BALANCE"
	COMMAND_TEXT_SETTING       = "COMMAND_TEXT_SETTING"
	COMMAND_TEXT_HELP          = "COMMAND_TEXT_HELP"
	COMMAND_TEXT_HISTORY       = "COMMAND_TEXT_HISTORY"
	COMMAND_TEXT_NOTIFICATIONS = "COMMAND_TEXT_NOTIFICATIONS"

	COMMAND_TEXT_NEW_COUNTERPARTY = "COMAND_TEXT_NEW_COUNTERPARTY"

	COMMAND_TEXT_SUBSCRIBE_TO_APP = "COMMAND_TEXT_SUBSCIBE_TO_APP"

	COMMAND_TEXT_I_AM_FINE_WITH_BOT = "COMMAND_TEXT_I_AM_FINE_WITH_BOT"

	COMMAND_TEXT_SEND_RECEIPT_BY_TELEGRAM = "COMMAND_TEXT_SEND_RECEIPT_BY_TELEGRAM"

	COMMAND_TEXT_SHOW_ALL_CONTACTS = "COMMAND_TEXT_SHOW_ALL_CONTACTS"
)

const (
	SMS_RECEIPT_YOU_GOT = "SMS_RECEIPT_YOU_GOT"
	SMS_RECEIPT_YOU_GAVE = "SMS_RECEIPT_YOU_GAVE"
	TELEGRAM_RECEIPT_YOU_GOT = "TELEGRAM_RECEIPT_YOU_GOT"
	TELEGRAM_RECEIPT_YOU_GAVE = "TELEGRAM_RECEIPT_YOU_GAVE"
)